sudo: required

language: generic
services: docker
env:
  global:
  - TZ='Europe/Oslo'
  - RELEASE_VERSION="$(git fetch --unshallow || true && git rev-list --count $TRAVIS_COMMIT)"
  - DOCKER_IMAGE_NAME="$TRAVIS_REPO_SLUG"
  - DOCKER_IMAGE_WITH_TAG="$DOCKER_IMAGE_NAME:$RELEASE_VERSION"
  - DOCKER_IMAGE_LATEST="$DOCKER_IMAGE_NAME:latest"

script: 
  - if [[ $TRAVIS_BRANCH =~ (^master) ]]; 
    then
      docker build -t "$DOCKER_IMAGE_WITH_TAG" . && docker tag "$DOCKER_IMAGE_WITH_TAG" "$DOCKER_IMAGE_LATEST";
    else 
      docker build -t "$DOCKER_IMAGE_NAME:$TRAVIS_BRANCH" .;
    fi
  
deploy:
  provider: script
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push "$DOCKER_IMAGE_NAME"
  on:
    all_branches: true